from __future__ import annotations

from flexrag.models.encoders import (
    HFClipEncoder,
    HFClipEncoderConfig,
    HFEncoder,
    HFEncoderConfig,
    LiteLLMEncoder,
    LiteLLMEncoderConfig,
    SentenceTransformerEncoder,
    SentenceTransformerEncoderConfig,
)
from flexrag.models.generators import (
    HFGenerator,
    HFGeneratorConfig,
    LiteLLMGenerator,
    LiteLLMGeneratorConfig,
)
from flexrag.models.scorers import (
    HFColBertScorer,
    HFColBertScorerConfig,
    HFCrossEncoderScorer,
    HFCrossEncoderScorerConfig,
    HFLogitsScorer,
    HFLogitsScorerConfig,
)
from flexrag.models.tokenizer import (
    HuggingFaceTokenizer,
    HuggingFaceTokenizerConfig,
    JiebaTokenizer,
    JiebaTokenizerConfig,
    MosesTokenizer,
    MosesTokenizerConfig,
    NLTKTokenizer,
    NLTKTokenizerConfig,
    SpaceTokenizer,
    SpaceTokenizerConfig,
    TikTokenTokenizer,
    TikTokenTokenizerConfig,
)
from flexrag.processors.chunkers import (
    CharChunker,
    CharChunkerConfig,
    DenseXChunker,
    DenseXChunkerConfig,
    LumberChunker,
    LumberChunkerConfig,
    RecursiveChunker,
    RecursiveChunkerConfig,
    SemanticChunker,
    SemanticChunkerConfig,
    SentenceChunker,
    SentenceChunkerConfig,
    TokenChunker,
    TokenChunkerConfig,
)
from flexrag.processors.rankers import (
    HFRanker,
    HFRankerConfig,
    LiteLLMRanker,
    LiteLLMRankerConfig,
    RankGPTRanker,
    RankGPTRankerConfig,
)
from flexrag.processors.refiners import (
    AbstractiveSummarizer,
    AbstractiveSummarizerConfig,
    ContextArranger,
    ContextArrangerConfig,
    RecompExtractiveSummarizer,
    RecompExtractiveSummarizerConfig,
)
from flexrag.retrievers.backends import (
    BM25SBackend,
    BM25SBackendConfig,
    ElasticBackend,
    ElasticBackendConfig,
    FaissBackend,
    FaissBackendConfig,
    LanceBackend,
    LanceBackendConfig,
)
from flexrag.retrievers.context_store import (
    LMDBContextStore,
    LMDBContextStoreConfig,
    SQLiteContextStore,
    SQLiteContextStoreConfig,
)

from .registry import Resources

Resources.register(
    "litellm_encoder",
    interface="encoder",
    config_class=LiteLLMEncoderConfig,
    default_runtime="async",
    parallel_safe=True,
)(LiteLLMEncoder)
Resources.register(
    "sentence_transformer_encoder",
    interface="encoder",
    config_class=SentenceTransformerEncoderConfig,
    default_runtime="process",
    parallel_safe=True,
)(SentenceTransformerEncoder)
Resources.register(
    "hf_encoder",
    interface="encoder",
    config_class=HFEncoderConfig,
    default_runtime="process",
    parallel_safe=True,
)(HFEncoder)
Resources.register(
    "hf_clip_encoder",
    interface="encoder",
    config_class=HFClipEncoderConfig,
    default_runtime="process",
    parallel_safe=True,
)(HFClipEncoder)
Resources.register(
    "litellm_generator",
    interface="generator",
    config_class=LiteLLMGeneratorConfig,
    default_runtime="async",
    parallel_safe=True,
    batching=False,
)(LiteLLMGenerator)
Resources.register(
    "hf_generator",
    interface="generator",
    config_class=HFGeneratorConfig,
    default_runtime="process",
    parallel_safe=True,
)(HFGenerator)
Resources.register(
    "hf_cross_encoder_scorer",
    interface="scorer",
    config_class=HFCrossEncoderScorerConfig,
    default_runtime="process",
    parallel_safe=True,
)(HFCrossEncoderScorer)
Resources.register(
    "hf_logits_scorer",
    interface="scorer",
    config_class=HFLogitsScorerConfig,
    default_runtime="process",
    parallel_safe=True,
)(HFLogitsScorer)
Resources.register(
    "hf_colbert_scorer",
    interface="scorer",
    config_class=HFColBertScorerConfig,
    default_runtime="process",
    parallel_safe=True,
)(HFColBertScorer)
Resources.register(
    "hf_ranker",
    interface="ranker",
    config_class=HFRankerConfig,
    batching=False,
)(HFRanker)
Resources.register(
    "rank_gpt_ranker",
    interface="ranker",
    config_class=RankGPTRankerConfig,
    batching=False,
)(RankGPTRanker)
Resources.register(
    "litellm_ranker",
    interface="ranker",
    config_class=LiteLLMRankerConfig,
    default_runtime="async",
    batching=False,
)(LiteLLMRanker)
Resources.register(
    "context_arranger",
    interface="refiner",
    config_class=ContextArrangerConfig,
    batching=False,
)(ContextArranger)
Resources.register(
    "abstractive_summarizer",
    interface="refiner",
    config_class=AbstractiveSummarizerConfig,
    batching=False,
)(AbstractiveSummarizer)
Resources.register(
    "extractive_summarizer",
    interface="refiner",
    config_class=RecompExtractiveSummarizerConfig,
    batching=False,
)(RecompExtractiveSummarizer)
Resources.register(
    "space_tokenizer",
    interface="tokenizer",
    config_class=SpaceTokenizerConfig,
    batching=False,
)(SpaceTokenizer)
Resources.register(
    "moses_tokenizer",
    interface="tokenizer",
    config_class=MosesTokenizerConfig,
    batching=False,
)(MosesTokenizer)
Resources.register(
    "nltk_tokenizer",
    interface="tokenizer",
    config_class=NLTKTokenizerConfig,
    batching=False,
)(NLTKTokenizer)
Resources.register(
    "jieba_tokenizer",
    interface="tokenizer",
    config_class=JiebaTokenizerConfig,
    batching=False,
)(JiebaTokenizer)
Resources.register(
    "hf_tokenizer",
    interface="tokenizer",
    config_class=HuggingFaceTokenizerConfig,
    batching=False,
)(HuggingFaceTokenizer)
Resources.register(
    "tiktoken_tokenizer",
    interface="tokenizer",
    config_class=TikTokenTokenizerConfig,
    batching=False,
)(TikTokenTokenizer)
Resources.register(
    "char_chunker",
    interface="chunker",
    config_class=CharChunkerConfig,
    batching=False,
)(CharChunker)
Resources.register(
    "token_chunker",
    interface="chunker",
    config_class=TokenChunkerConfig,
    batching=False,
)(TokenChunker)
Resources.register(
    "recursive_chunker",
    interface="chunker",
    config_class=RecursiveChunkerConfig,
    batching=False,
)(RecursiveChunker)
Resources.register(
    "sentence_chunker",
    interface="chunker",
    config_class=SentenceChunkerConfig,
    batching=False,
)(SentenceChunker)
Resources.register(
    "semantic_chunker",
    interface="chunker",
    config_class=SemanticChunkerConfig,
    batching=False,
)(SemanticChunker)
Resources.register(
    "lumber_chunker",
    interface="chunker",
    config_class=LumberChunkerConfig,
    batching=False,
)(LumberChunker)
Resources.register(
    "densex_chunker",
    interface="chunker",
    config_class=DenseXChunkerConfig,
    batching=False,
)(DenseXChunker)
Resources.register(
    "bm25s_backend",
    interface="collection_backend",
    config_class=BM25SBackendConfig,
    default_runtime="process",
)(BM25SBackend)
Resources.register(
    "faiss_backend",
    interface="collection_backend",
    config_class=FaissBackendConfig,
    default_runtime="process",
)(FaissBackend)
Resources.register(
    "elastic_backend",
    interface="collection_backend",
    config_class=ElasticBackendConfig,
    default_runtime="async",
)(ElasticBackend)
Resources.register(
    "lance_backend",
    interface="collection_backend",
    config_class=LanceBackendConfig,
    default_runtime="async",
)(LanceBackend)
Resources.register(
    "lmdb_context_store",
    interface="context_store",
    config_class=LMDBContextStoreConfig,
    batching=False,
)(LMDBContextStore)
Resources.register(
    "sqlite_context_store",
    interface="context_store",
    config_class=SQLiteContextStoreConfig,
    batching=False,
)(SQLiteContextStore)
