from .contextual_mc import (
    ContextualMCTask,
    ContextualMCTaskConfig,
    LongBenchV2Task,
    LongBenchV2TaskConfig,
)
from .contextual_qa import (
    ContextualQATask,
    ContextualQATaskConfig,
    GutenQATask,
    GutenQATaskConfig,
    LiteraryQATask,
    LiteraryQATaskConfig,
    LongBenchTask,
    LongBenchTaskConfig,
    MultihopRAGTask,
    MultihopRAGTaskConfig,
    NarrativeQATask,
    NarrativeQATaskConfig,
    SQuADTask,
    SQuADTaskConfig,
)
from .multisession_qa import (
    ConvoMemTask,
    ConvoMemTaskConfig,
    LoCoMoTask,
    LoCoMoTaskConfig,
    LongMemEvalTask,
    LongMemEvalTaskConfig,
)
from .open_qa import (
    BrowseCompTask,
    BrowseCompTaskConfig,
    BrowseCompZHTask,
    BrowseCompZHTaskConfig,
    OpenQATask,
    OpenQATaskConfig,
    SimpleQATask,
    SimpleQATaskConfig,
    UDAQATask,
    UDAQATaskConfig,
)
from .retrieval_task import (
    MLDRRetrievalTask,
    MLDRRetrievalTaskConfig,
    MSMARCORetrievalTask,
    MSMARCORetrievalTaskConfig,
    MTEBRetrievalTask,
    MTEBRetrievalTaskConfig,
    RetrievalTask,
    RetrievalTaskConfig,
)
from .task_base import TASKS, TaskBase, TaskBaseConfig

TaskConfig = TASKS.make_config()


__all__ = [
    "TaskBase",
    "TaskBaseConfig",
    "TASKS",
    "TaskConfig",
    "MTEBRetrievalTask",
    "MTEBRetrievalTaskConfig",
    "RetrievalTask",
    "RetrievalTaskConfig",
    "ContextualQATask",
    "ContextualQATaskConfig",
    "GutenQATask",
    "GutenQATaskConfig",
    "LiteraryQATask",
    "LiteraryQATaskConfig",
    "LongBenchTask",
    "LongBenchTaskConfig",
    "MultihopRAGTask",
    "MultihopRAGTaskConfig",
    "NarrativeQATask",
    "NarrativeQATaskConfig",
    "SQuADTask",
    "SQuADTaskConfig",
    "ConvoMemTask",
    "ConvoMemTaskConfig",
    "LoCoMoTask",
    "LoCoMoTaskConfig",
    "LongMemEvalTask",
    "LongMemEvalTaskConfig",
    "ContextualMCTask",
    "ContextualMCTaskConfig",
    "LongBenchV2Task",
    "LongBenchV2TaskConfig",
    "BrowseCompTask",
    "BrowseCompTaskConfig",
    "BrowseCompZHTask",
    "BrowseCompZHTaskConfig",
    "OpenQATask",
    "OpenQATaskConfig",
    "SimpleQATask",
    "SimpleQATaskConfig",
    "UDAQATask",
    "UDAQATaskConfig",
]
